version: "3.9"

services:
  devopsdb:
    image: rajaaganti/appstack:db
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root
      MYSQL_DATABASE: accounts
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork
    secrets:
      - mysql_root
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  application:
    image: rajaaganti/appstack:app
    ports:
      - "1111:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://devopsdb:3306/accounts?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD_FILE: /run/secrets/mysql_root
    networks:
      - mynetwork
    secrets:
      - mysql_root
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s

volumes:
  mysql-data:

networks:
  mynetwork:
    driver: overlay
    attachable: true

secrets:
  mysql_root:
    external: true
